In [2]:
import numpy as np


In [3]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape,Y.shape

((4, 2), (4, 1))

In [4]:
def sig(z):
    return 1/(1+np.exp(-z))

In [5]:
def derivateSig(z):
    return sig(z)*(1-sig(z))

In [9]:
#no hidden layer weights
weights = 2*np.random.random((2,1))-1
bias = 2*np.random.random(1)-1
lr = 0.001
weights,bias

(array([[-0.33119008],
        [-0.5618903 ]]),
 array([0.13616106]))

In [12]:
#forward propogation without any hidden layer
for i in range(1000):
    weights = weights - lr*changes
    bias_change = 0.0
    output0 = X
    output = sig(np.dot(output0,weights) +bias)
    
    first_term = output-Y
    input_for_last_layer = np.dot(output0,weights)+bias
    second_term = derivateSig(input_for_last_layer)
    first_two = first_term*second_term
    first_two.shape
    changes = np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0] * output0[j][i]
    for j in range(4):
        bias_change += first_two[j][0]*1
    bias = bias - lr * bias_change
    output = sig(np.dot(X, weights) + bias)
weights,bias, output

(array([[-0.24099171],
        [-0.43896471]]),
 array([-0.19016824]),
 array([[0.4526007 ],
        [0.34770716],
        [0.39384938],
        [0.29522836]]))