In [1]:
import numpy as np
a = [1,2,3,4]
b = np.array(a)
print(b)

[1 2 3 4]


In [2]:
a = [1,2,3,'5',5.3]
b = np.array(a, dtype = int)

print(b)

[1 2 3 5 5]


In [3]:
a = [1,2,3,'5',5.3]
b = np.array(a*3, dtype = int)
print(b)

[1 2 3 5 5 1 2 3 5 5 1 2 3 5 5]


In [4]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [5]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [6]:
b = np.zeros((3, 4), dtype = int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
b = np.full((3, 3), 5, dtype = int)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
b = np.empty(4, dtype = int)
print(b)

[1 2 3 4]


In [9]:
np.random.randint(10, 4)


ValueError: low >= high

In [ ]:
np.arange(10)


In [ ]:
b = np.arange(2,10)
b

In [ ]:
b = np.arange(2,10,2)
b

In [ ]:
b  = np.linspace(2, 10, 5, dtype = int, endpoint = False)
b

In [ ]:
b = np.identity(3)
b

In [ ]:
b = np.eye(3,4)
b

In [ ]:
b = np.random.rand(1,2)
b

In [ ]:
b = np.random.randint(5,20,3)
b

In [ ]:
import numpy as np

li = [1, 2, 3, 4, 5]
arr = np.array(li)

print(li)
print(arr)

In [ ]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

In [ ]:
print(li[3])
print(arr[3])
print(li[1:4])
print(arr[1:4])

In [ ]:
li_2d = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)


In [ ]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)


In [ ]:
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2, 1])

In [ ]:
print(li_2d[1][:3])
print(arr_2d[1, :3])


In [ ]:
ex = li_2d[0:3]
print(x)
y = x[2]
print(y)


In [ ]:
print(li_2d[0:3][0])


In [ ]:
print(arr_2d[2:4, 1:3])
print(li_2d[2:4][1:3])

In [ ]:
li = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

In [ ]:
li = [i+1 for i in li]
li

In [ ]:
a = a + 1
a


In [ ]:
c = a + b
c

In [ ]:
d = a - b
d


In [ ]:
e = a * b
e

In [ ]:
e = a * b
e

In [ ]:
g = a // b
g

In [ ]:
h = a ** b
h

In [ ]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

In [ ]:
a > b


In [ ]:
a

In [ ]:
print(np.logical_or(a, b))
print(np.logical_and(a, b))


In [ ]:
a[2] = 0
print(a)
print(np.logical_not(a))

In [ ]:
import numpy as np

a = np.array(['t', 'b', 'r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1, 20, 8)

print(a)
print(b)

In [ ]:
print(b > 10)


In [ ]:
bool_arr = b > 10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

In [ ]:
new_arr = b[b > 10]
new_arr

In [ ]:
new_arr = b[(b > 10) & (b < 18)]
new_arr


In [ ]:
print(b)
c = b
c

In [ ]:
c[:3] = 19
print(c)
c[c > 15] = 100
c

In [ ]:
print(b)


In [ ]:
print(b[b == 100])

In [ ]:
ind = np.where(b == 100)
ind

In [ ]:
ind = np.where(b == 100)
print(ind)
print(a[ind])

In [10]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [13]:
a = np.random.randint(1,30,(5,6))
a

array([[ 4, 16, 14, 20, 21, 17],
       [ 8, 20, 14, 18, 14, 27],
       [18, 10, 17, 27, 14, 15],
       [14, 28,  3,  1, 17,  7],
       [22, 23, 13,  5, 12, 25]])

In [14]:
bool_arr = a>20
bool_arr

array([[False, False, False, False,  True, False],
       [False, False, False, False, False,  True],
       [False, False, False,  True, False, False],
       [False,  True, False, False, False, False],
       [ True,  True, False, False, False,  True]])

In [15]:
b = a[bool_arr]
print(b)

[21 27 27 28 22 23 25]


In [18]:
x = a
x

array([[ 4, 16, 14, 20, 21, 17],
       [ 8, 20, 14, 18, 14, 27],
       [18, 10, 17, 27, 14, 15],
       [14, 28,  3,  1, 17,  7],
       [22, 23, 13,  5, 12, 25]])

In [20]:
x[bool_arr] = 100
print(x)

[[  4  16  14  20 100  17]
 [  8  20  14  18  14 100]
 [ 18  10  17 100  14  15]
 [ 14 100   3   1  17   7]
 [100 100  13   5  12 100]]


In [21]:
b = np.random.randint(1,10,(2,2))
b

array([[2, 4],
       [4, 3]])

In [30]:
b_bool= np.array([[True,False],[False,True],[True, False]])
print(b_bool)

[[ True False]
 [False  True]
 [ True False]]


In [77]:
x

array([[  4,  16,  14,  20, 100,  17],
       [  8,  20,  14,  18,  14, 100],
       [ 18,  10,  17, 100,  14,  15],
       [ 14, 100,   3,   1,  17,   7],
       [100, 100,  13,   5,  12, 100]])

In [78]:

x_boolarr = x[:,5] == 100
x_boolarr


array([False,  True, False, False,  True])

In [80]:
x[x_boolarr,5] =999999
print(x)

[[     4     16     14     20    100     17]
 [     8     20     14     18     14 999999]
 [    18     10     17    100     14     15]
 [    14    100      3      1     17      7]
 [   100    100     13      5     12 999999]]


In [21]:
import csv
import numpy as np
with open('resource/year2017.csv') as obj:
    data = csv.DictReader(obj,skipinitialspace = True)
    
    killed = []
    wounded = []
    country = []
#     print(data)
    for i in data:
        killed.append(i["Killed"])
        wounded.append(i['Wounded'])
        country.append(i['Country'])
    np_killed = np.array(killed)
    np_wounded = np.array(wounded)
    
    np_killed[np_killed == ''] = '0.0'
    np_wounded[np_wounded == ''] = '0.0'
    
    np_killed = np.array(np_killed,dtype = float)
    np_wounded = np.array(np_wounded,dtype = float)
    
    kw = np_killed+np_wounded
    np_country = np.array(country)
    
    bool_cnt = np_country == 'India'
    ans = kw[bool_cnt]
    
    print(np.sum(ans))
    print(np.sum(kw))

1167.0
51372.0


In [ ]:
import numpy as np
import csv

with open('terrorismData.csv', encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    killed=[]
    wounded=[]
    city=[]
    for row in file_data:
        if 'India' in row['Country'] and 'Unknown' not in row['City']:
            city.append(row['City'])
            wounded.append(row['Wounded'])
            killed.append(row['Killed'])
    np_wounded=np.array(wounded)
    np_killed=np.array(killed)
    np_city=np.array(city)
    
    np_killed[np_killed=='']='0.0'
    np_wounded[np_wounded=='']='0.0'
    np_killed=np.array(np_killed, dtype='float')
    np_wounded=np.array(np_wounded, dtype='float')
    np_casuality=np.array(np_wounded+np_killed, dtype='int')
    citydic={}
    for i in range(len(np_city)):
        if np_city[i] in citydic:
            citydic[np_city[i]]+=np_casuality[i]
        else:
            citydic[np_city[i]]=np_casuality[i]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]